#!/usr/bin/env bash
# Generated by cgraf78/actions checkout-installer. Do not edit.
#
# This file is deliberately self-contained. From a real repository checkout it
# delegates immediately. When downloaded or piped to Bash, it creates or safely
# updates a durable checkout and delegates to the same repository-owned script.

{
  set -euo pipefail
  caller_umask=$(umask)
  umask 077

  checkout_repo='cgraf78/vscode-exts'
  checkout_slug='vscode-exts'
  checkout_ref='main'
  checkout_delegate='support/install-checkout.sh'
  default_repo_url="https://github.com/${checkout_repo}.git"

  die() {
    printf 'install.sh: %s\n' "$*" >&2
    exit 1
  }

  require_delegate() {
    local checkout_root=$1 delegate_path=${2:-$checkout_delegate} delegate

    delegate="$checkout_root/$delegate_path"
    [[ -f "$delegate" && ! -L "$delegate" ]] ||
      die "checkout installer is missing: $delegate"
  }

  exec_bootstrap_git() {
    [[ -n ${CHECKOUT_INSTALLER_GIT_HOME:-} ]] ||
      die 'internal Git configuration home is not set'
    unset GIT_ALTERNATE_OBJECT_DIRECTORIES
    unset GIT_COMMON_DIR
    unset GIT_CEILING_DIRECTORIES
    unset GIT_CONFIG
    unset GIT_CONFIG_COUNT
    unset GIT_CONFIG_GLOBAL
    unset GIT_CONFIG_NOSYSTEM
    unset GIT_CONFIG_PARAMETERS
    unset GIT_CONFIG_SYSTEM
    unset GIT_DIR
    unset GIT_DISCOVERY_ACROSS_FILESYSTEM
    unset GIT_EXEC_PATH
    unset GIT_GRAFT_FILE
    unset GIT_IMPLICIT_WORK_TREE
    unset GIT_INDEX_FILE
    unset GIT_INTERNAL_SUPER_PREFIX
    unset GIT_NAMESPACE
    unset GIT_NO_REPLACE_OBJECTS
    unset GIT_OBJECT_DIRECTORY
    unset GIT_PREFIX
    unset GIT_PROXY_COMMAND
    unset GIT_ALLOW_PROTOCOL
    unset GIT_PROTOCOL_FROM_USER
    unset GIT_REPLACE_REF_BASE
    unset GIT_SHALLOW_FILE
    unset GIT_SSH
    unset GIT_SSH_VARIANT
    unset GIT_SSL_NO_VERIFY
    unset GIT_TEMPLATE_DIR
    unset GIT_WORK_TREE
    GIT_CONFIG_GLOBAL=/dev/null \
      GIT_CONFIG_NOSYSTEM=1 \
      GIT_PROTOCOL_FROM_USER=0 \
      GIT_TERMINAL_PROMPT=0 \
      HOME="$CHECKOUT_INSTALLER_GIT_HOME" \
      XDG_CONFIG_HOME="$CHECKOUT_INSTALLER_GIT_HOME/xdg" \
      exec git \
      -c core.hooksPath=/dev/null \
      -c core.fsmonitor=false \
      -c submodule.recurse=false \
      -c fetch.recurseSubmodules=false \
      -c protocol.allow=never \
      -c protocol.file.allow=always \
      -c protocol.https.allow=always \
      -c protocol.ssh.allow=always \
      "$@"
  }

  bootstrap_git() {
    local isolated_home status

    isolated_home=$(mktemp -d \
      "${TMPDIR:-/tmp}/cgraf78-checkout-installer.git.XXXXXX") ||
      die 'cannot create isolated Git configuration home'
    if (CHECKOUT_INSTALLER_GIT_HOME="$isolated_home" \
      exec_bootstrap_git "$@"); then
      status=0
    else
      status=$?
    fi
    rm -rf -- "$isolated_home"
    return "$status"
  }

  trusted_checkout_git() {
    local checkout_root=$1
    shift

    bootstrap_git -c "safe.directory=$checkout_root" \
      -C "$checkout_root" "$@"
  }

  network_git() {
    local status

    active_git_home=$(mktemp -d \
      "${TMPDIR:-/tmp}/cgraf78-checkout-installer.git.XXXXXX") ||
      die 'cannot create isolated Git configuration home'

    (
      GIT_ASKPASS=/bin/false
      SSH_ASKPASS=/bin/false
      GIT_SSH_COMMAND='ssh -oBatchMode=yes'
      CHECKOUT_INSTALLER_GIT_HOME=$active_git_home
      export CHECKOUT_INSTALLER_GIT_HOME
      export GIT_ASKPASS SSH_ASKPASS GIT_SSH_COMMAND
      exec_bootstrap_git -c credential.helper= "$@"
    ) </dev/null &
    active_child_pid=$!
    set +e
    wait "$active_child_pid"
    status=$?
    active_child_pid=
    set -e
    rm -rf -- "$active_git_home"
    active_git_home=
    return "$status"
  }

  require_tracked_delegate() {
    local checkout_root=$1 delegate_path=${2:-$checkout_delegate}

    require_delegate "$checkout_root" "$delegate_path"
    bootstrap_git -C "$checkout_root" ls-files --error-unmatch -- \
      "$delegate_path" >/dev/null 2>&1 ||
      die "checkout installer is not tracked: $checkout_root/$delegate_path"
  }

  require_tree_delegate() {
    local checkout_root=$1 revision=$2
    local delegate_path=${3:-$checkout_delegate} entry mode type object path

    entry=$(bootstrap_git -C "$checkout_root" ls-tree "$revision" -- \
      "$delegate_path") ||
      die "cannot inspect checkout installer in revision $revision"
    IFS=$' \t' read -r mode type object path <<<"$entry"
    [[ ("$mode" == 100644 || "$mode" == 100755) &&
      "$type" == blob && -n "$object" && "$path" == "$delegate_path" ]] ||
      die "checkout installer is missing from revision $revision: $delegate_path"
  }

  checkout_source_root() {
    local source_path=$1 script_dir top

    [[ -f "$source_path" && ! -L "$source_path" ]] || return 1
    [[ ${source_path##*/} == install.sh ]] || return 1
    script_dir=$(cd -P -- "$(dirname "$source_path")" && pwd -P) || return 1
    top=$(trusted_checkout_git "$script_dir" \
      rev-parse --show-toplevel 2>/dev/null) ||
      return 1
    top=$(cd -P -- "$top" && pwd -P) || return 1
    [[ "$top" == "$script_dir" ]] || return 1
    [[ -f "$top/install.sh" && ! -L "$top/install.sh" ]] || return 1
    [[ -f "$top/$checkout_delegate" && ! -L "$top/$checkout_delegate" ]] ||
      return 1
    trusted_checkout_git "$top" ls-files --error-unmatch -- \
      install.sh "$checkout_delegate" >/dev/null 2>&1 || return 1
    printf '%s\n' "$top"
  }

  exec_delegate() {
    local checkout_root=$1
    shift

    require_delegate "$checkout_root"
    umask "$caller_umask"
    exec "$BASH" "$checkout_root/$checkout_delegate" "$@"
  }

  # A generated installer committed at the repository root keeps ordinary
  # checkout installs fast and offline. Piped Bash has no regular source file,
  # while a downloaded standalone copy has no adjacent delegate; both continue
  # into the managed-checkout bootstrap below.
  script_source=${BASH_SOURCE[0]:-}
  if [[ -n "$script_source" ]] &&
    script_dir=$(checkout_source_root "$script_source"); then
    exec_delegate "$script_dir" "$@"
  fi

  command -v git >/dev/null 2>&1 || die 'git is required for a piped install'
  [[ -n ${HOME:-} ]] || die 'HOME is not set'

  repo_url=${CGRAF78_CHECKOUT_INSTALL_REPO_URL:-$default_repo_url}
  checkout_dir=${CGRAF78_CHECKOUT_INSTALL_DIR:-}
  if [[ -z "$checkout_dir" ]]; then
    if [[ ${XDG_DATA_HOME:-} == /* ]]; then
      data_home=$XDG_DATA_HOME
    else
      data_home=$HOME/.local/share
    fi
    checkout_dir="$data_home/cgraf78/checkouts/$checkout_slug"
  fi

  case "$checkout_dir" in
    '' | / | */ | *//* | */./* | */. | */../* | */..)
      die "managed checkout path must be a normalized absolute path: $checkout_dir"
      ;;
    /*) ;;
    *)
      die "managed checkout path must be absolute: $checkout_dir"
      ;;
  esac
  [[ "$checkout_dir" != *$'\n'* && "$checkout_dir" != *$'\r'* ]] ||
    die 'managed checkout path must not contain line breaks'

  checkout_parent=${checkout_dir%/*}
  checkout_name=${checkout_dir##*/}
  [[ -n "$checkout_parent" ]] || checkout_parent=/
  mkdir -p "$checkout_parent" ||
    die "cannot create managed checkout parent: $checkout_parent"
  [[ -d "$checkout_parent" ]] ||
    die "managed checkout parent is not a directory: $checkout_parent"
  checkout_parent=$(cd -P -- "$checkout_parent" && pwd -P) ||
    die "cannot resolve managed checkout parent: $checkout_parent"
  checkout_dir="$checkout_parent/$checkout_name"

  staging=
  publish_identity=
  active_child_pid=
  active_git_home=
  lock_dir="$checkout_parent/.${checkout_name}.install.lock"
  update_transaction="$checkout_parent/.${checkout_name}.install.transaction"
  update_identity=
  update_next="$update_transaction/next"
  update_previous="$update_transaction/previous"
  update_candidate_head="$update_transaction/candidate-head"
  update_previous_head="$update_transaction/previous-head"
  update_recorded_delegate=
  update_next_marker=.git/cgraf78-update-next-identity
  update_previous_marker=.git/cgraf78-update-previous-identity
  update_transaction_created=0
  lock_held=0

  # shellcheck disable=SC2329 # Called by cleanup through the EXIT trap.
  release_lock() {
    if [[ "$lock_held" -eq 1 ]]; then
      rmdir "$lock_dir" 2>/dev/null || true
      lock_held=0
    fi
  }

  # shellcheck disable=SC2329 # Installed as the EXIT trap below.
  recover_staging_location() {
    local expected nested

    [[ -n "$publish_identity" && -f "$publish_identity" &&
      ! -L "$publish_identity" ]] || return 0
    expected="$checkout_dir/.git/cgraf78-publish-identity"
    nested="$checkout_dir/${staging##*/}/.git/cgraf78-publish-identity"
    if [[ -f "$expected" && "$publish_identity" -ef "$expected" ]]; then
      staging=$checkout_dir
    elif [[ -n "$staging" && -f "$nested" &&
      "$publish_identity" -ef "$nested" ]]; then
      staging=${nested%/.git/cgraf78-publish-identity}
    fi
  }

  create_identity_marker() {
    local identity=$1 marker=$2

    if ln "$identity" "$marker" 2>/dev/null; then
      return 0
    fi
    [[ ! -e "$marker" && ! -L "$marker" ]] || return 1
    ln -s "$identity" "$marker"
  }

  validate_managed_checkout() {
    local candidate=$1 top branch origin status

    [[ -d "$candidate" && ! -L "$candidate" ]] ||
      die "destination is not a managed Git checkout: $candidate"
    top=$(bootstrap_git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) ||
      die "destination is not a managed Git checkout: $candidate"
    top=$(cd -P -- "$top" && pwd -P) ||
      die "cannot resolve managed Git checkout: $candidate"
    candidate=$(cd -P -- "$candidate" && pwd -P) ||
      die "cannot resolve managed Git checkout: $candidate"
    [[ "$top" == "$candidate" ]] ||
      die "destination is not the root of its Git checkout: $candidate"

    origin=$(bootstrap_git -C "$candidate" remote get-url origin 2>/dev/null) ||
      die "managed Git checkout has no origin: $candidate"
    [[ "$origin" == "$repo_url" ]] ||
      die "managed Git checkout origin differs: $origin"
    branch=$(bootstrap_git -C "$candidate" symbolic-ref --quiet --short HEAD 2>/dev/null) ||
      die "managed Git checkout is detached: $candidate"
    [[ "$branch" == "$checkout_ref" ]] ||
      die "managed Git checkout branch differs: $branch"
    status=$(bootstrap_git -C "$candidate" status --porcelain \
      --untracked-files=normal) ||
      die "cannot inspect managed Git checkout: $candidate"
    [[ -z "$status" ]] ||
      die "managed Git checkout is dirty; refusing to update: $candidate"
  }

  locate_update_identity() {
    local candidate count=0

    update_identity=
    for candidate in "$update_transaction"/identity.*; do
      [[ -e "$candidate" || -L "$candidate" ]] || continue
      count=$((count + 1))
      update_identity=$candidate
    done
    [[ "$count" -eq 1 && -f "$update_identity" &&
      ! -L "$update_identity" ]] || return 1
    update_recorded_delegate=$(sed -n '5p' "$update_identity")
    case "$update_recorded_delegate" in
      '' | install.sh | -* | . | .. | /* | ./* | */./* | */. | *[!A-Za-z0-9._/-]* | *//* | ../* | */../* | */..)
        return 1
        ;;
    esac
    [[ $(sed -n '1p' "$update_identity") == 'cgraf78 checkout installer update transaction v1' &&
    $(sed -n '2p' "$update_identity") == "$checkout_dir" &&
    $(sed -n '3p' "$update_identity") == "$checkout_repo" &&
    $(sed -n '4p' "$update_identity") == "$checkout_ref" ]]
  }

  update_identity_matches() {
    local marker=$1

    [[ -f "$update_identity" && ! -L "$update_identity" &&
      -f "$marker" &&
      "$update_identity" -ef "$marker" ]]
  }

  reclaim_nested_update_checkout() {
    local nested=$1 destination=$2 marker=$3

    [[ ! -e "$destination" && ! -L "$destination" ]] || return 1
    update_identity_matches "$nested/$marker" || return 1
    mv -n "$nested" "$destination" || return 1
    update_identity_matches "$destination/$marker"
  }

  validate_recorded_checkout() {
    local candidate=$1 head_file=$2 require_recorded_delegate=$3 actual expected

    [[ -f "$head_file" && ! -L "$head_file" ]] || return 1
    expected=$(sed -n '1p' "$head_file")
    [[ "$expected" =~ ^[0-9a-f]{40}([0-9a-f]{24})?$ ]] || return 1
    if ! (
      validate_managed_checkout "$candidate"
      if [[ "$require_recorded_delegate" == true ]]; then
        require_tree_delegate "$candidate" HEAD "$update_recorded_delegate"
        require_tracked_delegate "$candidate" "$update_recorded_delegate"
      fi
    ); then
      return 1
    fi
    actual=$(bootstrap_git -C "$candidate" rev-parse HEAD) || return 1
    [[ "$actual" == "$expected" ]]
  }

  # Finish or roll back an update transaction using inode identity markers.
  # Hard links are preferred, with symbolic links as a fallback on filesystems
  # that reject hard links. This also handles a transaction left after SIGKILL
  # once the user has confirmed no installer is active and removed the stale
  # directory lock.
  recover_update_transaction() {
    local current_next current_previous nested_next nested_previous
    local previous_next previous_previous

    [[ -e "$update_transaction" || -L "$update_transaction" ]] || return 0
    if [[ ! -d "$update_transaction" || -L "$update_transaction" ]]; then
      printf 'install.sh: update transaction is not a regular directory: %s\n' \
        "$update_transaction" >&2
      return 1
    fi
    if ! locate_update_identity; then
      if [[ "$update_transaction_created" -eq 1 ]] &&
        rmdir "$update_transaction" 2>/dev/null; then
        update_transaction_created=0
        return 0
      fi
      printf 'install.sh: update transaction has no valid ownership identity: %s\n' \
        "$update_transaction" >&2
      return 1
    fi

    current_next="$checkout_dir/$update_next_marker"
    current_previous="$checkout_dir/$update_previous_marker"
    nested_next="$checkout_dir/${update_next##*/}"
    nested_previous="$checkout_dir/${update_previous##*/}"
    previous_next="$update_previous/$update_next_marker"
    previous_previous="$update_previous/$update_previous_marker"

    # Portable mv nests a source when a same-UID race creates the target
    # directory. Reclaim only a child carrying this transaction's identity,
    # and leave the foreign target itself untouched.
    if [[ ! -e "$update_next" && ! -L "$update_next" &&
      -d "$nested_next" && ! -L "$nested_next" ]] &&
      update_identity_matches "$nested_next/$update_next_marker"; then
      reclaim_nested_update_checkout "$nested_next" "$update_next" \
        "$update_next_marker" || return 1
    fi
    if [[ ! -e "$update_previous" && ! -L "$update_previous" &&
      -d "$nested_previous" && ! -L "$nested_previous" ]] &&
      update_identity_matches "$nested_previous/$update_previous_marker"; then
      reclaim_nested_update_checkout "$nested_previous" "$update_previous" \
        "$update_previous_marker" || return 1
    fi

    if [[ -e "$update_previous" || -L "$update_previous" ]]; then
      if [[ ! -d "$update_previous" || -L "$update_previous" ]]; then
        printf 'install.sh: update rollback is not a regular directory: %s\n' \
          "$update_previous" >&2
        return 1
      fi
      if update_identity_matches "$current_next"; then
        # The fully validated candidate reached the stable path. Publication
        # is the commit point, so finish retiring the old checkout.
        validate_recorded_checkout "$checkout_dir" \
          "$update_candidate_head" true ||
          return 1
        rm -rf -- "$update_previous" || return 1
        rm -f -- "$current_next" || return 1
      elif [[ ! -e "$checkout_dir" && ! -L "$checkout_dir" ]] &&
        update_identity_matches "$previous_previous"; then
        # The old checkout moved but candidate publication did not complete.
        validate_recorded_checkout "$update_previous" \
          "$update_previous_head" false || return 1
        mv -n "$update_previous" "$checkout_dir" || return 1
        if ! update_identity_matches "$current_previous"; then
          if [[ -d "$nested_previous" && ! -L "$nested_previous" ]]; then
            reclaim_nested_update_checkout "$nested_previous" \
              "$update_previous" "$update_previous_marker" || return 1
          fi
          return 1
        fi
        rm -f -- "$current_previous" || return 1
      else
        printf 'install.sh: cannot safely recover managed checkout update: %s\n' \
          "$checkout_dir" >&2
        return 1
      fi
    elif update_identity_matches "$current_previous"; then
      # The transaction stopped before moving the old checkout.
      validate_recorded_checkout "$checkout_dir" \
        "$update_previous_head" false ||
        return 1
      rm -f -- "$current_previous" || return 1
    elif update_identity_matches "$current_next"; then
      # The old checkout was already retired; finish the committed update.
      validate_recorded_checkout "$checkout_dir" \
        "$update_candidate_head" true ||
        return 1
      rm -f -- "$current_next" || return 1
    elif [[ -e "$current_next" || -L "$current_next" ||
      -e "$current_previous" || -L "$current_previous" ||
      -e "$previous_next" || -L "$previous_next" ||
      -e "$previous_previous" || -L "$previous_previous" ]]; then
      printf 'install.sh: update transaction identity does not match checkout: %s\n' \
        "$checkout_dir" >&2
      return 1
    fi

    if [[ -e "$update_next" || -L "$update_next" ]]; then
      if [[ ! -d "$update_next" || -L "$update_next" ]]; then
        printf 'install.sh: staged update is not a regular directory: %s\n' \
          "$update_next" >&2
        return 1
      fi
      rm -rf -- "$update_next" || return 1
    fi
    [[ ! -e "$update_previous" && ! -L "$update_previous" ]] || return 1
    rm -f -- "$update_candidate_head" "$update_previous_head" || return 1
    rm -f -- "$update_identity" || return 1
    rmdir "$update_transaction" || return 1
    update_transaction_created=0
  }

  # shellcheck disable=SC2329 # Installed as the EXIT trap below.
  cleanup() {
    local status=$?

    trap - EXIT HUP INT TERM
    recover_update_transaction || true
    recover_staging_location
    if [[ -n "$active_git_home" && -d "$active_git_home" &&
      ! -L "$active_git_home" ]]; then
      rm -rf -- "$active_git_home"
    fi
    if [[ -n "$staging" && -d "$staging" && ! -L "$staging" ]]; then
      rm -rf -- "$staging"
    fi
    if [[ -n "$publish_identity" && -f "$publish_identity" &&
      ! -L "$publish_identity" ]]; then
      rm -f -- "$publish_identity"
    fi
    release_lock
    exit "$status"
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  wait_for_pid_exit() {
    local pid=$1

    for _ in {1..100}; do
      kill -0 "$pid" 2>/dev/null || return 0
      command sleep 0.01
    done
    return 1
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  terminate_snapshot_child() {
    local child=$1 parent=$2 signal=$3

    # Keep the parent alive long enough to reap the child. Killing a whole tree
    # in one fire-and-forget pass can orphan a still-exiting descendant, which
    # remains observable as a zombie under minimal container init processes.
    kill -s "$signal" "$child" 2>/dev/null || true
    wait_for_pid_exit "$child" && return 0
    kill -s KILL "$child" 2>/dev/null || true
    wait_for_pid_exit "$child" && return 0
    printf 'install.sh: child process %s was not reaped by parent %s after %s and KILL\n' \
      "$child" "$parent" "$signal" >&2
    return 1
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  signal_snapshot_children() {
    local parent=$1 signal=$2 snapshot=$3 child children live_parent failed=0

    children=$(printf '%s\n' "$snapshot" |
      command awk -v parent="$parent" '$2 == parent { print $1 }')
    for child in $children; do
      signal_snapshot_children "$child" "$signal" "$snapshot" || failed=1
      live_parent=$(command ps -o ppid= -p "$child" 2>/dev/null || true)
      live_parent=${live_parent//[[:space:]]/}
      if [[ "$live_parent" == "$parent" ]]; then
        terminate_snapshot_child "$child" "$parent" "$signal" || failed=1
      fi
    done
    return "$failed"
  }

  # shellcheck disable=SC2329 # Reached by the signal-trap call chain below.
  signal_process_tree() {
    local root=$1 signal=$2 snapshot

    local failed=0

    snapshot=$(command ps -eo pid=,ppid= 2>/dev/null || true)
    signal_snapshot_children "$root" "$signal" "$snapshot" || failed=1
    # Cancellation must not leave the active delegate running. If an
    # uncooperative parent failed to reap a descendant even after escalation,
    # the caller above reports that limitation before this final best-effort
    # root termination.
    kill -s "$signal" "$root" 2>/dev/null || true
    return "$failed"
  }

  # shellcheck disable=SC2329 # Installed as the signal traps below.
  forward_signal() {
    local signal=$1 status=$2 child_signal=$1

    trap - HUP INT TERM
    if [[ -n "$active_child_pid" ]]; then
      # Non-job-control Bash starts asynchronous children with SIGINT ignored.
      # Use a catchable termination signal for those owned children while the
      # bootstrap still reports the conventional interrupt status to callers.
      [[ "$signal" == INT ]] && child_signal=TERM
      if ! signal_process_tree "$active_child_pid" "$child_signal"; then
        printf 'install.sh: process-tree cleanup was incomplete after %s\n' \
          "$signal" >&2
      fi
      wait "$active_child_pid" 2>/dev/null || true
      active_child_pid=
    fi
    exit "$status"
  }

  trap cleanup EXIT
  trap 'forward_signal HUP 129' HUP
  trap 'forward_signal INT 130' INT
  trap 'forward_signal TERM 143' TERM

  if ! mkdir "$lock_dir" 2>/dev/null; then
    die "another install may be using the managed checkout lock: $lock_dir; if no install is running, remove that exact empty directory with rmdir and retry"
  fi
  lock_held=1

  recover_update_transaction ||
    die "cannot recover interrupted managed checkout update: $update_transaction"

  if [[ -e "$checkout_dir" || -L "$checkout_dir" ]]; then
    validate_managed_checkout "$checkout_dir"
    printf 'install.sh: updating %s\n' "$checkout_dir"
    mkdir "$update_transaction" ||
      die "cannot create update transaction: $update_transaction"
    update_transaction_created=1
    update_identity=$(mktemp "$update_transaction/identity.XXXXXX") ||
      die "cannot create update transaction identity: $update_identity"
    if ! printf '%s\n%s\n%s\n%s\n%s\n' \
      'cgraf78 checkout installer update transaction v1' \
      "$checkout_dir" "$checkout_repo" "$checkout_ref" \
      "$checkout_delegate" >"$update_identity"; then
      rm -f -- "$update_identity"
      die "cannot write update transaction identity: $update_transaction"
    fi
    update_recorded_delegate=$checkout_delegate
    network_git -c init.templateDir= \
      clone --quiet --single-branch --branch "$checkout_ref" \
      --no-tags -- "$repo_url" "$update_next" </dev/null ||
      die "cannot clone $checkout_repo branch $checkout_ref for update"
    validate_managed_checkout "$update_next"
    require_tree_delegate "$update_next" HEAD
    require_tracked_delegate "$update_next"
    current_head=$(bootstrap_git -C "$checkout_dir" rev-parse HEAD) ||
      die "cannot resolve managed checkout revision: $checkout_dir"
    candidate_head=$(bootstrap_git -C "$update_next" rev-parse HEAD) ||
      die "cannot resolve staged managed checkout revision: $update_next"
    bootstrap_git -C "$update_next" merge-base --is-ancestor \
      "$current_head" "$candidate_head" ||
      die "managed Git checkout cannot fast-forward: $checkout_dir"
    if [[ "$current_head" != "$candidate_head" ]]; then
      printf '%s\n' "$candidate_head" >"$update_candidate_head" ||
        die "cannot record staged managed checkout revision: $candidate_head"
      printf '%s\n' "$current_head" >"$update_previous_head" ||
        die "cannot record previous managed checkout revision: $current_head"
      create_identity_marker \
        "$update_identity" "$update_next/$update_next_marker" ||
        die 'cannot prepare staged update identity'
      create_identity_marker \
        "$update_identity" "$checkout_dir/$update_previous_marker" ||
        die 'cannot prepare managed checkout rollback identity'
      mv -n "$checkout_dir" "$update_previous" ||
        die "cannot stage previous managed checkout: $checkout_dir"
      update_identity_matches "$update_previous/$update_previous_marker" ||
        die "cannot verify previous managed checkout identity: $update_previous"
      mv -n "$update_next" "$checkout_dir" ||
        die "cannot publish managed checkout update: $checkout_dir"
      update_identity_matches "$checkout_dir/$update_next_marker" ||
        die "cannot verify published managed checkout update: $checkout_dir"
    fi
    recover_update_transaction ||
      die "cannot finish managed checkout update: $update_transaction"
    validate_managed_checkout "$checkout_dir"
    require_tracked_delegate "$checkout_dir"
  else
    staging=$(mktemp -d "$checkout_parent/.${checkout_slug}.clone.XXXXXX") ||
      die "cannot create checkout staging directory under $checkout_parent"
    printf 'install.sh: cloning %s to %s\n' "$checkout_repo" "$checkout_dir"
    network_git -c init.templateDir= \
      clone --quiet --depth 1 --single-branch --branch "$checkout_ref" \
      --no-tags -- "$repo_url" "$staging" </dev/null ||
      die "cannot clone $checkout_repo branch $checkout_ref"
    validate_managed_checkout "$staging"
    require_tree_delegate "$staging" HEAD
    require_tracked_delegate "$staging"
    [[ ! -e "$checkout_dir" && ! -L "$checkout_dir" ]] ||
      die "managed checkout destination appeared during clone: $checkout_dir"
    publish_identity=$(mktemp "$checkout_parent/.${checkout_slug}.publish.XXXXXX") ||
      die "cannot create checkout publication identity under $checkout_parent"
    create_identity_marker \
      "$publish_identity" "$staging/.git/cgraf78-publish-identity" ||
      die 'cannot prepare checkout publication identity'
    mv -n "$staging" "$checkout_dir" ||
      die "cannot publish managed checkout: $checkout_dir"
    if [[ ! -f "$checkout_dir/.git/cgraf78-publish-identity" ||
      ! "$publish_identity" -ef "$checkout_dir/.git/cgraf78-publish-identity" ]]; then
      recover_staging_location
      die "managed checkout destination appeared during publication: $checkout_dir"
    fi
    rm -f -- "$checkout_dir/.git/cgraf78-publish-identity" "$publish_identity"
    publish_identity=
    staging=
    validate_managed_checkout "$checkout_dir"
    require_tracked_delegate "$checkout_dir"
  fi

  require_delegate "$checkout_dir"
  umask "$caller_umask"
  set +e
  "$BASH" "$checkout_dir/$checkout_delegate" "$@" <&0 &
  active_child_pid=$!
  wait "$active_child_pid"
  delegate_status=$?
  active_child_pid=
  set -e
  exit "$delegate_status"
}
